name: green-perception
channels: [pytorch, conda-forge, nvidia]
dependencies:
  - python=3.11
  - pytorch-cuda=12.1
  - pytorch=2.4
  - torchvision
  - cudatoolkit
  - opencv
  - lightgbm
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - pyyaml
  - rich
  - pycocotools
  - pytest
  - pip
  - pip:
      - ultralytics==8.*
      - pynvml
      - onnxruntime-gpu
